---
 - hosts: all
   tasks:
      - name: SELINUX permissive mode - Disable SELinux
        selinux:
          policy: targeted
          state: permissive 
     
      - name: Enable the br_netfilter module for cluster communication
        modprobe: 
          name: bridge-nf-call-iptables
          state: present
          params: "1"
     
      - name: Add Docker Repo
        yum_repository:
          name: Docker
          description: Docker CE Repository
          baseurl: https://download.docker.com/linux/centos/docker-ce.repo
     
      - name: Kubernetes repo 
        yum_repository:
          name: Kubernetes
          baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          gpgcheck: no 
          gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg, https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          repo_gpgcheck: no 
          enabled: yes

      - name: Ensure that the Docker dependencies are satisfied
        yum:
          name: "{{ packages }}"
          state: present
        vars: 
          packages:
          - device-mapper-persistent-data
          - lvm2
          - docker-ce
     
      - name: Cgroup driver for dockerfile
        replace:
          path: /usr/lib/systemd/system/docker.service
          regexp: '/^ExecStart/ s/$'
          replace: '--exec-opt native.cgroupdriver=systemd'
     
      - name: Reload Systemd
        systemd:
          state: restarted
          daemon_reload: yes 
     
      - name: Enable Docker 
        systemd:
            name: docker
            enabled: yes
       
      - name: Install Kubernetes
        yum:
          state: present
          name: "{{ packages }}"
        vars:
          packages:
          - kubelet
          - kubeadm
          - kubectl
     
      - name: Enable Kubernetes
        systemd: 
          enabled: yes
          name: kubelet





    
#- Enable the br_netfilter module for cluster communication.

#    modprobe br_netfilter
 #   echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
#- Ensure that the Docker dependencies are satisfied.

 #   yum install -y yum-utils device-mapper-persistent-data lvm2

#- Add the Docker repo and install Docker.
 #   yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  #  yum install -y docker-ce

#- Set the cgroup driver for Docker to systemd, then reload systemd, enable and start Docker
 #   sed -i '/^ExecStart/ s/$/ --exec-opt native.cgroupdriver=systemd/' /usr/lib/systemd/system/docker.service
  #  systemctl daemon-reload
   # systemctl enable docker --now

#- Add the repo for Kubernetes

   # cat << EOF > /etc/yum.repos.d/kubernetes.repo
    #[kubernetes]
    #name=Kubernetes
    #baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    #enabled=1
    #gpgcheck=0
    #repo_gpgcheck=0
    #gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
    #https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg   
    #EOF   

#- Install Kubernetes.
  
 # yum install -y kubelet kubeadm kubectl

#- Enable the kubelet service. The kubelet service will fail to start until the cluster is initialized, this is expected.

 # systemctl enable kubelet